version: "3.8"
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:6.0.18
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - graylog
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
  #Graylog Data Node: https://hub.docker.com/r/graylog/graylog-datanode
  datanode:
    image: graylog/graylog-datanode:6.1
    hostname: datanode
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      GRAYLOG_DATANODE_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8999:8999/tcp # DataNode API
      - 9200:9200/tcp
      - 9300:9300/tcp
    networks:
      - graylog
    volumes:
      - graylog-datanode:/var/lib/graylog-datanode
    restart: on-failure
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    hostname: server
    image: graylog/graylog:6.1
    # To install Graylog Open: "graylog/graylog:6.1"
    depends_on:
      mongodb:
        condition: service_started
      datanode:
        condition: service_started
    entrypoint: /usr/bin/tini -- /docker-entrypoint.sh
    environment:
      GRAYLOG_NODE_ID_FILE: /usr/share/graylog/data/config/node-id
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:5500
      GRAYLOG_MONGODB_URI: mongodb://mongodb:27017/graylog
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      # Password: "admin"
      GRAYLOG_ROOT_PASSWORD_SHA2: 1b291f63cd6d53d426ef18abac5b446714f780b8be382db70698f1f85b09e3ab
      GRAYLOG_HTTP_EXTERNAL_URI: http://10.10.130.25:5500/
    ports:
      # Graylog web interface and REST API
      - 5500:5500/tcp
      - 5044:5044/tcp
      - 5140:5140/tcp
      - 5140:5140/udp
      - 12201:12201/tcp
      - 12201:12201/udp
      - 13301:13301/tcp
      - 13302:13302/tcp
    restart: on-failure
    networks:
      - graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
networks:
  graylog:
    driver: bridge
volumes:
  mongodb_data: null
  mongodb_config: null
  graylog-datanode: null
  graylog_data: null
