version: "3.8"
services:
  postgres-server:
    container_name: postgres-server
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: passwd!Q
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ubuntu-7.0-latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: passwd!Q
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:
      - ./volumes/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/zabbix/protocolo/snmptraps:/var/lib/zabbix/snmptraps
  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.0-latest
    restart: always
    ports:
      - 80:8080/tcp
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: passwd!Q
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: Asia/Seoul # 시간대 설정 (한국)
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
  zabbix-snmptraps:
    container_name: zabbix-snmptraps
    image: zabbix/zabbix-snmptraps
    restart: always
    volumes:
      - /var/zabbix/protocolo/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/zabbix/protocolo/mibs:/usr/share/snmp/mibs:ro
    ports:
      - 161:161/udp
      - 162:162/udp
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000 # Grafana 웹 포트 매핑 (기본 포트)
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app # Grafana의 Zabbix 플러그인 설치
    depends_on:
      - postgres-server
      - zabbix-server
networks:
  default: null
